# Site settings
name: Travelogue
description: "A blog chronicling the good, the beautiful, the tasty, the many flights of stairs one must carry IKEA furniture up, and the ugly."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://missmaddielou.github.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: :title/

pagination: true
paginate: 8
paginate_path: page/:num/

author:
    name: "Madeline"
    email: ""
    uri: "https://github.com/SalGnt"

sass:
    sass_dir: _sass
    style: compressed

defaults:
    - scope:
          path: "_posts"
          type: "posts"
      values:
          reading_time: true
          # Meta
          show_tags: true
          show_categories: true
          # Social
          share_buttons: true
          disqus: false

plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
